# Generated by Django 3.1.5 on 2021-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('book_name', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('explain', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('category_rank', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('category_name', models.TextField(blank=True)),
            ],
        ),
    ]
